# Set the required Fablo organization environment

@token = {{enroll.response.body.token}}

###

# Retrieve the authentication token using the set organization's admin secret
# @name enroll
POST http://{{host}}:{{port}}/user/enroll
Content-Type: application/json
Authorization: "Bearer "

< {{auth-file}}

###

# @name RequestEntry
POST http://{{host}}:{{port}}/invoke/{{channel}}/{{chaincode}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "method": "RequestEntry",
    "args": ["1", "1"],
    "transient": {}
}
